from nyuntam_adapt.tasks.text_generation import CausalLLM
from nyuntam_adapt.tasks.image_classification import ImageClassification
from nyuntam_adapt.tasks.timm_image_classification import TimmforImageClassification
from nyuntam_adapt.tasks.text_classification import SequenceClassification
from nyuntam_adapt.tasks.summarization import Seq2Seq
from nyuntam_adapt.tasks.translation import Translation
from nyuntam_adapt.tasks.question_answering import QuestionAnswering
from nyuntam_adapt.tasks.params import create_instance, AdaptParams

